export const routes = {
  home: "/",
  klasser: "/forerkortklasser",
  klasse: (slug: string) => `/forerkortklasser/${slug}`,
  taForerkort: "/ta-forerkort",
  trafikaltGrunnkurs: "/trafikalt-grunnkurs",
  ovelseskjoring: "/ovelseskjoring",
  teoriprove: "/teoriprove",
  oppkjoring: "/oppkjoring",
  kostnad: "/kostnad",
  tilhenger: "/tilhenger",
  motorsykkelOgMoped: "/motorsykkel-og-moped",
  verktoy: "/verktoy",
  verktoyItem: (slug: string) => `/verktoy/${slug}`,
  guider: "/guider",
  guide: (slug: string) => `/guider/${slug}`,
  kilderOgMetode: "/kilder-og-metode",
  om: "/om",
  kontakt: "/kontakt",
  personvern: "/personvern",
} as const;
